name: Optimizer
version: '${project.version}'
main: it.blacked.optimizer.Optimizer
api-version: '1.8'
commands:
  optimize:
    usage: /optimize [help | starttask | stoptask | manualtask | info]
    permission: optimizer.use
permissions:
  optimizer.use:
    default: op